# Generated by Django 6.0.7 on 2026-07-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IphoneListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('nama_toko', models.CharField(max_length=200)),
                ('rating_produk', models.FloatField(default=0.0)),
                ('has_rating', models.BooleanField(default=False)),
                ('produk_terjual', models.IntegerField(default=0)),
                ('kategori_seri', models.CharField(max_length=100)),
                ('kategori_varian', models.CharField(max_length=100)),
                ('penyimpanan', models.CharField(max_length=20)),
                ('battery_health', models.FloatField(blank=True, null=True)),
                ('bh_imputed', models.BooleanField(default=False)),
                ('harga', models.BigIntegerField()),
                ('wilayah_toko', models.CharField(max_length=100)),
                ('link_pembelian', models.URLField(max_length=2000)),
                ('kondisi', models.CharField(choices=[('like_new', 'Like New'), ('mulus', 'Mulus'), ('normal', 'Normal'), ('bekas', 'Bekas'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('generasi', models.IntegerField()),
                ('is_pro', models.BooleanField(default=False)),
                ('penyimpanan_gb', models.IntegerField(default=128)),
                ('dokumen_teks', models.TextField()),
                ('trust_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-trust_score', '-battery_health'],
            },
        ),
    ]
