# Generated by Django 6.0.7 on 2026-07-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iphonelisting',
            name='garansi',
            field=models.CharField(choices=[('resmi', 'Resmi'), ('inter', 'Inter'), ('beacukai', 'Beacukai'), ('tidak_ada', 'Tidak Ada')], default='tidak_ada', max_length=20),
        ),
        migrations.AddField(
            model_name='iphonelisting',
            name='varian_model',
            field=models.CharField(choices=[('reguler', 'Reguler'), ('mini', 'Mini'), ('plus', 'Plus'), ('pro', 'Pro'), ('pro_max', 'Pro Max')], default='reguler', max_length=20),
        ),
    ]
